name: news notify

on:
  schedule:
    - cron: "0 23 * *"
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install packages
        run: pip install feedparser requests

      - name: send news
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python news_notify.py
